apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: literary-ant-go 
  janus-idp.io/tekton: literary-ant-go
  backstage.io/kubernetes-id: literary-ant-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: literary-ant-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  